#!/bin/bash
# based off of src: https://gist.github.com/gene1wood/6530100

if ! hash openssl 2> /dev/null; then
    echo "openssl not installed..."
    exit 1
fi

while read line; do
    if [ -z "$TEXT" ]; then
        if [ "$line" == "-----BEGIN CERTIFICATE-----" ]; then
            action="x509"
        elif [ "$line" == "-----BEGIN CERTIFICATE REQUEST-----" ]; then
            action="req"
        elif [ "$line" == "-----BEGIN RSA PRIVATE KEY-----" ]; then
            action="rsa"
        fi
        TEXT="$line\n"
    else
        TEXT="$TEXT$line\n"
    fi
done < `"${1:-/dev/stdin}" > /dev/null 2>&1`

if [ -n "$TEXT" ] && [ -n "$action" ]; then
    printf '%b' "$TEXT" | openssl $action -in /dev/stdin -noout -text
else
    echo -n | openssl s_client -connect $1:443 | openssl x509 -text
fi
