#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import re
import sys
sys.dont_write_bytecode = True

from ruamel import yaml
from attrdict import AttrDict
from argparse import ArgumentParser

FILENAME = '{common_name}@{timestamp}.yml'
YML_TEXT = '''
{common_name}@{timestamp}:
  authority:
    digicert:
      order_id: {order_id}
  common_name: {common_name}
  expiry: {expiry}
  sans: null
  timestamp: {timestamp}
'''

if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument(
        'common_name',
        help='common_name')
    parser.add_argument(
        'timestamp',
        type=int,
        help='timestamp')
    parser.add_argument(
        'order_id',
        type=int,
        help='order_id')
    parser.add_argument(
        'expiry',
        type=int,
        help='expiry')

    ns = parser.parse_args()
    filename = FILENAME.format(**ns.__dict__)
    yml_text = YML_TEXT.format(**ns.__dict__)

    with open(filename, 'w') as f:
        f.write(yml_text)

    yml = yaml.safe_load(open(filename))
    body = yml['{common_name}@{timestamp}'.format(**ns.__dict__)]
    assert body['common_name'] == ns.common_name
    assert body['timestamp'] == ns.timestamp
    assert body['authority']['digicert']['order_id'] == ns.order_id
    assert body['expiry'] == ns.expiry

